"use client"

import React from 'react';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { FileText, Download, Share2 } from 'lucide-react';
import { Button } from '@/components/ui/button';

interface StrategicMemoProps {
  memo: string;
  companyName: string;
}

export function StrategicMemo({ memo, companyName }: StrategicMemoProps) {
  const formatMemo = (text: string) => {
    return text.split('\n').map((line, index) => {
      if (line.startsWith('#') || line.includes(':')) {
        const parts = line.split(':');
        if (parts.length > 1) {
          return (
            <div key={index} className="mt-4 mb-2">
              <span className="font-headline font-bold text-primary block text-sm uppercase tracking-wide">
                {parts[0].replace(/^#+\s*/, '').trim()}
              </span>
              <p className="text-sm leading-relaxed text-foreground mt-1">
                {parts.slice(1).join(':').trim()}
              </p>
            </div>
          );
        }
      }
      return line.trim() ? (
        <p key={index} className="text-sm leading-relaxed text-foreground mb-3">
          {line}
        </p>
      ) : null;
    });
  };

  return (
    <Card className="shadow-lg border-primary/10 overflow-hidden">
      <CardHeader className="bg-primary text-primary-foreground flex flex-row items-center justify-between p-6">
        <div className="flex items-center gap-3">
          <FileText className="h-5 w-5 opacity-80" />
          <CardTitle className="text-xl font-headline">{companyName} — Strategic Memo</CardTitle>
        </div>
        <div className="flex gap-2">
          <Button variant="ghost" size="icon" className="text-white hover:bg-white/10">
            <Download className="h-4 w-4" />
          </Button>
          <Button variant="ghost" size="icon" className="text-white hover:bg-white/10">
            <Share2 className="h-4 w-4" />
          </Button>
        </div>
      </CardHeader>
      <CardContent className="p-8 bg-white font-body">
        <div className="max-w-3xl mx-auto prose prose-sm">
          {memo ? formatMemo(memo) : (
            <div className="flex flex-col items-center justify-center py-20 text-muted-foreground">
              <p>Analyzing strategy frameworks...</p>
            </div>
          )}
        </div>
        <div className="mt-8 pt-6 border-t border-slate-100 flex justify-between items-center text-[10px] text-muted-foreground">
          <span>Generated by PlatformLens</span>
          <span>Platform Strategy Analysis</span>
        </div>
      </CardContent>
    </Card>
  );
}
